name = "device-editor"
main = "worker/worker.js"
compatibility_date = "2025-03-12"
compatibility_flags = ["nodejs_compat"]

[vars]
UPSTREAM_REPO = "clydebarrow/device-configs"
BASE_BRANCH = "main"

[[kv_namespaces]]
binding = "SESSIONS"
id = "9f41a0d949f44ab282d9865de743f1dc"
preview_id = "67974c12ef4d41eb9338a695d54bf45c"

[assets]
directory = "./assets"
binding = "ASSETS"

