name = "device-editor"
main = "worker/index.js"
compatibility_date = "2025-03-12"
compatibility_flags = ["nodejs_compat"]

[vars]
GITHUB_CLIENT_ID = "Iv23liylBD7j9P27QzWk"
GITHUB_CLIENT_SECRET = "36d955d3f110a1388a99c4ae9df05ebf792ebac2"
UPSTREAM_REPO = "clydebarrow/device-configs"
BASE_BRANCH = "main"

[[kv_namespaces]]
binding = "SESSIONS"
id = "9f41a0d949f44ab282d9865de743f1dc"
preview_id = "67974c12ef4d41eb9338a695d54bf45c"
