name = "device-editor"
main = "worker/index.js"
compatibility_date = "2025-03-12"
compatibility_flags = ["nodejs_compat"]

[vars]
GITHUB_CLIENT_ID = "Iv23li8mQtjbH2U0DlAE"
GITHUB_CLIENT_SECRET = "c46c7f7053578b07bfee1f972532451977a03205"
UPSTREAM_REPO = "clydebarrow/device-configs"
BASE_BRANCH = "main"
PRIVATE_KEY='''
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAzLmowbq9tDRF0wwcig/dL4OP8aNoRvGT2oaLe+CYo4Y/H/v0
MdrwuKYKECGpGr9qhbqMcV3MT3dmA3LOIgHEIeKz3XZkinv9Q8VVB/Inz0pK6koK
DxzbRUfWp1xKrd2m19dqECUck9y8uhNLALw/9KNXQqIxQHoGuujD9EBo61uGB2HC
Pc8Es9leiMF+QUIl49+lW1dLa9a4yKpvSdzhACM0ex1nDpK2ApI02pPkxO1sfgS7
4Cpv1NADQxuVPv3sofLJzvwiSeYSuvv4QtCsxVK64bAIRN+ETtUV0YD7Q7U1U+is
KrOfMB+M+Q1ghmu5bqbcF4uoVgWFRAYavJnGTwIDAQABAoIBAQC4ntFF67657M3v
FiQCiW3hNFayBbe7Co5Yai8NhqyAA0eX82HzN8sP6YR3qbNTUL2iXWnbrkfafgU8
JOMpncge+s9TbzoZ/NiXrjQRV1p5QDkw8ZYCrPY8kx1Ljho2kwWr7jJS3vTXjx+O
+mkP/7P5TPgbOiMKT0EUe2aDNTaozyFJ+v/ZfoDnMHCdWq5ouM56fhQFGSTAywpP
rtApYMPi9bL/K6RUm5Qh8L2Xnzd1PhXopchC24DQrT8yUV582eVb6tK8ovwwlwGz
72bYHS7fHlVH5XZ+bG3RKF2uyzJgNa3uIpIblxH6byLigl8ZpjbicsZrxUfq4ID5
OpNSFNGpAoGBAPi/ZFGWudKli0JKCjyYIm0m+D4eEEXcGl0Yy1nR64GvbHoe+qkN
dP2M0L9Rjk4HZzAVY49dvm3yl3qlbR24fSvFHgL9Idu0dy+EkBOkQYM1gt2hw46L
u7DSHk06zgj4EkjHci11P+xxXpp9868ZIq33+WzeA3SHCEk04HDVG+IlAoGBANKx
sSc4xyOSi+EcfsPkTiESMuDt/vvrb5tNNfRB7+uL8ggae9PQDqFntpsyV/mTeJzP
FMeL55wtfGNiODl/E7SKRUuBtPOLifwMz9y87pvHkkSDZuoKj441uR+PwG8qBNWM
giMc3gtfBFLHCTV1E5LW7AxAGHz+eW8udkR4FmpjAoGADB2GTVMCCfh2J+xjQ0BF
rPtQ6/Wa5UwrHI2wmddXmSFqLyiDHOjC4faR1D+sprBFnlnsV3dBZymBpz+XaPMr
ZY5cP9kEZScNBwt12P8PEczxasoONEsqARq6zxgmINm0SkcskHo9es6qxOuNiuG2
hrKlO2A02uAYzzf8FoLKsOECgYA8eAUI5bG5kuCUbfIv1IFb2nZBuex5brusTb+T
Z60s5BBFpRwu0UKxritpZUx8c4elMYWcM5n4Z9GQUGskjUUhhqGWpxZA46ZpcV/i
0VKF4QQop7HMr9U9kkucNEydWujiRR5AZ5OOnemGvFr3Pa+tcAN1DJw6m2pMr3//
7Js6UwKBgE0srgW2Lrh7b+Gxe8Ur5HFYMQHtqHvwMK5mLZowY/2swGVu5XjONoDa
Ta0VkobIGdjMk8QP0HIFFs53lg31GQm5eWc4IZHmTQ0JtHO3Ya4/jNyeKMkONbDR
k+ebraZsplJQG+3dgoGh3Wq3abKm/GAqkci6776oRLfMMaH0s41b
-----END RSA PRIVATE KEY-----
'''

[[kv_namespaces]]
binding = "SESSIONS"
id = "9f41a0d949f44ab282d9865de743f1dc"
preview_id = "67974c12ef4d41eb9338a695d54bf45c"
